-- public.users definition

-- Drop table

-- DROP TABLE public.users;

-- public.users definition

-- Drop table

-- DROP TABLE public.users;

CREATE TABLE public.users (
                              id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                              email varchar(255) NOT NULL,
                              "name" varchar(255) NOT NULL,
                              "password" varchar(255) NOT NULL,
                              CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email),
                              CONSTRAINT users_pkey PRIMARY KEY (id)
);


INSERT INTO public.users
(id,  email,name ,password)
VALUES(1, 'admin@admin.com', 'admin','$2a$10$sbKkcUBetZI3mE.J1vQjDeKpttFsrvpBR/8rEKmtCYsFStlU0mHna');