-- public.roles definition

-- Drop table

-- DROP TABLE public.roles;

CREATE TABLE public.roles (
                              id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                              "name" varchar(255) NOT NULL,
                              CONSTRAINT roles_pkey PRIMARY KEY (id),
                              CONSTRAINT ukofx66keruapi6vyqpv6f2or37 UNIQUE (name)
);
-- public.users_roles definition

-- Drop table

-- DROP TABLE public.users_roles;

CREATE TABLE public.users_roles (
                                    user_id int8 NOT NULL,
                                    role_id int8 NOT NULL,
                                    CONSTRAINT fk2o0jvgh89lemvvo17cbqvdxaa FOREIGN KEY (user_id) REFERENCES public.users(id),
                                    CONSTRAINT fkj6m8fwv7oqv74fcehir1a9ffy FOREIGN KEY (role_id) REFERENCES public.roles(id)
);

INSERT INTO public.roles (id,"name") values (1,'ROLE_ADMIN');
INSERT INTO public.users_roles ("user_id","role_id") values (1,1);
